ROUTINE SourceCodeManager.scm

main
q

/// d load^SourceCodeManager.scm("<package name>")
load(projectName) PUBLIC
{
    d ##class(SourceCodeManager.Main).ImportSourceFiles(projectName, 0)
}

/// d import^SourceCodeManager.scm("<package name>")
import(projectName) PUBLIC
{
    d ##class(SourceCodeManager.Main).ImportSourceFiles(projectName)
}

/// d update^SourceCodeManager.scm("<package name>")
update(projectName) PUBLIC
{
    d ##class(SourceCodeManager.Main).UpdateSource(projectName)
}
